version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: issueDive-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: issue_dive
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        - DB_URL=${SPRING_DATASOURCE_URL}
        - DB_USER=${SPRING_DATASOURCE_USERNAME}
        - DB_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    container_name: issueDive-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    command: ./gradlew bootRun
    tty: true

volumes:
  mysql-data:
