version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: issueDive-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: issue_dive
      # 일반 사용자 추가하지 않거나 별도의 사용자명으로 변경
      # 예를 들어 USER는 issueuser 등으로 변경 가능
      # MYSQL_USER: issueuser
      # MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: issueDive-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    command: ./gradlew bootRun
#    volumes:
#      - ./:/app
    tty: true

volumes:
  mysql-data:
