name: CI Docker Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-build-action@v2

      - name: Build Docker image
        # GitHub Secrets를 환경 변수로 설정하고,
        # docker build 명령어에 --build-arg로 전달합니다.
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker build -t issue-dive-app \
            --build-arg DB_URL="$DB_URL" \
            --build-arg DB_USER="$DB_USER" \
            --build-arg DB_PASSWORD="$DB_PASSWORD" \
            .

      - name: Run tests inside Docker container
        run: |
          docker run --rm issue-dive-app ./gradlew test
