name: IssueDive Deploy to Production Server

# main 브랜치에 푸시(보통 dev -> main으로 PR이 merge될 때)될 때 실행됩니다.
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        # SSH를 통해 서버에 원격 접속하여 명령어를 실행해주는 Action
        uses: appleboy/ssh-action@master
        with:
          # GitHub Secrets에 등록할 정보들
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # 서버에 접속해서 실행할 스크립트
          script: |
            # 1. Docker Hub에 로그인
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            # 2. 최신 Docker 이미지 받아오기
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/issuedive:latest
            
            # 3. 기존에 실행 중인 앱 컨테이너가 있다면 중지하고 삭제 (최초 실행 시 오류가 나지 않도록 || true 추가)
            docker stop issuedive-app || true
            docker rm issuedive-app || true
            
            # 4. 최신 이미지로 새로운 앱 컨테이너 실행
            # 이전에 생성한 Docker 네트워크와 .env 파일을 사용합니다.
            docker run -d --name issuedive-app \
            -p 8080:8080 \
            --network issue-dive-net \
            --env-file /home/ec2-user/.env \
            ${{ secrets.DOCKERHUB_USERNAME }}/issuedive:latest